### ISSUE TITLE
CustomMM2ReplicationPoliecy not working for MM2GroupOffsetSync jar

### ISSUE THREAD

**Issue by nandaloussiBabylon** [aws-samples/mirrormaker2-msk-migration#3]
hi,

I have used the `com.amazonaws.kafka.samples.CustomMM2ReplicationPolicy` class in my mirrormaker2 job so the topics in my target cluster are named exactly the same as my source cluster, however upon running the following command i get the following error:

```
java -jar /opt/MM2GroupOffsetSync-1.0-SNAPSHOT.jar -cgi MY-CONSUMER-GROUP -src SOURCE -pfp /conf/consumer.properties -rpc com.amazonaws.kafka.samples.CustomMM2ReplicationPolicy
```

```
[2020-11-11 17:33:01,111] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - ERROR java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: Failed altering consumer group offsets for the following partitions: [SOURCE.topic1-0, SOURCE.topic2-0, SOURCE.TOPIC3-0]

Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: Failed altering consumer group offsets for the following partitions: [SOURCE.topic1-0, SOURCE.topic2-0, SOURCE.TOPIC3-0]
```

Why is it trying to look for topics in my target cluster with the source cluster named prepended to it?

**Comment by rcchakr** [comment]
Can you provide the entire log file?

**Comment by nandaloussiBabylon** [comment]
```
[2020-11-11 20:50:09,562] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - INFO ConsumerGroupDescriptions for consumer group MY_CONSUMER_GROUP - {MY_CONSUMER_GROUP=(groupId=MY_CONSUMER_GROUP, isSimpleConsumerGroup=true, members=, partitionAssignor=, state=Dead, coordinator=127.0.0.1:32403 (id: 3 rack: null), authorizedOperations=null)}

[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.protocol' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.login.refresh.window.factor' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.login.refresh.min.period.seconds' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.login.refresh.buffer.seconds' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.enabled.protocols' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.kerberos.ticket.renew.window.factor' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.kerberos.kinit.cmd' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.truststore.type' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.kerberos.ticket.renew.jitter' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.keystore.type' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.trustmanager.algorithm' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.keymanager.algorithm' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.kerberos.min.time.before.relogin' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'sasl.login.refresh.window.jitter' was supplied but isn't a known config.
[2020-11-11 20:50:09,563] (org.apache.kafka.clients.admin.AdminClientConfig) - WARN The configuration 'ssl.endpoint.identification.algorithm' was supplied but isn't a known config.
[2020-11-11 20:50:29,566] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - INFO 1605127829566 - Translated offsets for consumer group from checkpoint MY_CONSUMER_GROUP - {SOURCE_CLUSTER.MY_CONSUMER_GROUP-store.service.questionnaire-repartition-0=OffsetAndMetadata{offset=549408, leaderEpoch=null, metadata=''}, SOURCE_CLUSTER.topic.service.pa-questionnaire-0=OffsetAndMetadata{offset=1348019, leaderEpoch=null, metadata=''}}

[2020-11-11 20:50:29,569] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - INFO Consumer Group Offsets at destination for consumer group id MY_CONSUMER_GROUP - {}

[2020-11-11 20:50:29,569] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - INFO No Consumer Group offsets for specified consumer group id MY_CONSUMER_GROUP. Returning translated consumer offsets.

[2020-11-11 20:50:29,572] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - ERROR java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: Failed altering consumer group offsets for the following partitions: [SOURCE_CLUSTER.MY_CONSUMER_GROUP-store.service.questionnaire-repartition-0, SOURCE_CLUSTER.topic.service.pa-questionnaire-0]
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at com.amazonaws.kafka.samples.ConsumerOffsetsSync.updateConsumerGroupOffsets(ConsumerOffsetsSync.java:107)
	at com.amazonaws.kafka.samples.ConsumerOffsetsSync.run(ConsumerOffsetsSync.java:124)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: Failed altering consumer group offsets for the following partitions: [SOURCE_CLUSTER.MY_CONSUMER_GROUP-store.service.questionnaire-repartition-0, SOURCE_CLUSTER.topic.service.pa-questionnaire-0]

[2020-11-11 20:50:29,575] (com.amazonaws.kafka.samples.ConsumerOffsetsSync) - INFO ConsumerGroupDescriptions for consumer group MY_CONSUMER_GROUP - {MY_CONSUMER_GROUP=(groupId=MY_CONSUMER_GROUP, isSimpleConsumerGroup=true, members=, partitionAssignor=, state=Dead, coordinator=127.0.0.1:32403 (id: 3 rack: null), authorizedOperations=null)}
```

**Comment by nandaloussiBabylon** [comment]
after doing some local testing, the error no longer persists when i add the following changes to the ConsumerPffsetsSync.java source code:
```
            for (Map.Entry<TopicPartition, OffsetAndMetadata> entry : translatedOffsets.entrySet()) {
                String topic = entry.getKey().topic();
                String cluster = (String) mm2config.get("source.cluster.alias");

                if (topic.startsWith(cluster)) {
                    topic = topic.replaceFirst(cluster + ".", "");
                }

                cleanedTranslatedOffsets.put(new TopicPartition(topic, entry.getKey().partition()), entry.getValue());
            }
```

it basically removes the source cluster string from the partition name

**Comment by angeloskaltsikis** [comment]
@nandaloussiBabylon Hey mate,
good to see you here as well.
I am sharing the following information, even if I know it may be off-topic here , in order to unblock you till this is resolved .
We have managed to deploy the MirrorMaker 2.0 with Strimzi and achieve the same behaviour by using the class defined in https://github.com/strimzi/mirror-maker-2-extensions && https://github.com/strimzi/strimzi-kafka-operator/pull/3423 .

**Comment by nandaloussiBabylon** [comment]
Hey @angeloskaltsikis . lol yeah looks like we're working on something very similiar. i'm actually using the same approach. my mm2 strimzi application is using the IdentityReplicationPolicy class which as it happens is exactly the same as the CustomReplication Policy here. The issue is how the offsetSync application pulls out the topic names stored in the internal.offsets topic.

any feedback @rcchakr . i also noticed that the application only takes in one consumer-id (cannot batch). thats an issues for us because we have almost 1000 consumers.

second i often have to restart the application in order for it to pick up offset diffs.

**Comment by angeloskaltsikis** [comment]
> is how the offsetSync application pulls out the topic names stored in the internal.offsets topic

Haha indeed yes we are working on the same things right now. So to help you with what you are asking as well, we faced exactly the same limitation so we went one step further and decided to ditch this repository applications (and use it only as information to help us during the mirroring and clients cutover) and build a Strimzi docker image based on Kafka 2.7 RC (due to the (offset sync native functionality)[https://cwiki.apache.org/confluence/display/KAFKA/KIP-545%3A+support+automated+consumer+offset+sync+across+clusters+in+MM+2.0]) and it is working perfectly!
I would be happy to share more information but let's do it somewhere else in order to not spam this project.

**Comment by rcchakr** [comment]
> Hey @angeloskaltsikis . lol yeah looks like we're working on something very similiar. i'm actually using the same approach. my mm2 strimzi application is using the IdentityReplicationPolicy class which as it happens is exactly the same as the CustomReplication Policy here. The issue is how the offsetSync application pulls out the topic names stored in the internal.offsets topic.
> 
> any feedback @rcchakr . i also noticed that the application only takes in one consumer-id (cannot batch). thats an issues for us because we have almost 1000 consumers.
> 
> second i often have to restart the application in order for it to pick up offset diffs.

This was only meant as a sample, so it needs to be adapted to multiple consumers. Also, as suggested, with 2.7.0, this is not needed anymore. Application restarts should not be needed with this. In general, if you follow the directions at https://amazonmsk-labs.workshop.aws/en/migration/mirrormaker2.html it should work. Can you also post your mirror source connector configuration?

**Comment by Constantin07** [comment]
Hi @angeloskaltsikis just out of curiosity - have you used Kafka 2.7 RC MM2 binary (with built-in offset sync support) with previous versions of Kafka (source/destination) clusters (aka 2.4 or 2.6) ?
I'm wondering if newer MM2 version works with older Kafka clusters (automatic offset sync ) ...
